ПЕРВЫЙ ПРИМЕР

In [2]:
print('решение игры в доминирующих стратегиях')

решение игры в доминирующих стратегиях


In [3]:
import numpy as np

In [5]:
size = 10**4
a = np.random.normal(size=(size, size))
b = np.random.normal(size=(size, size))

In [8]:
%%time
np.linalg.inv(a)

CPU times: user 2min 4s, sys: 1.38 s, total: 2min 5s
Wall time: 16.6 s


array([[-0.11093954,  0.0763212 , -0.03677498, ..., -0.00673454,
         0.01649824,  0.02510601],
       [-0.00955657,  0.02066519, -0.00115256, ...,  0.00040442,
        -0.00081485,  0.00462756],
       [ 0.03860697, -0.00731323,  0.00905598, ...,  0.00746635,
        -0.02413508, -0.02115099],
       ...,
       [-0.02587041,  0.01323787, -0.01057828, ...,  0.00276189,
        -0.00136823,  0.00086748],
       [ 0.01018004, -0.0031304 , -0.00346739, ...,  0.01198456,
        -0.00643815,  0.00273251],
       [-0.05817066,  0.02747684, -0.01422911, ..., -0.00457817,
         0.0139673 ,  0.01333884]])

In [12]:
game1 = np.array([[0, 1],
                  [-1, 0]],
                dtype=np.float32)
game1

array([[ 0.,  1.],
       [-1.,  0.]], dtype=float32)

In [22]:
strategies = np.argmax(game1, axis=0)
strategies

array([0, 0])

In [20]:
result = np.all(strategies == strategies[0])
result

True

In [21]:
strategies[0]

0

In [23]:
a = np.array([[-4, -1],[-7, -2]])
b = np.array([[-4, -7],[-1, -2]])

a,b

(array([[-4, -1],
        [-7, -2]]),
 array([[-4, -7],
        [-1, -2]]))

In [24]:
strategies1 = np.argmax(a, axis=0)
strategies1

array([0, 0])

In [25]:
strategies2 = np.argmax(b, axis=1)
strategies2

array([0, 0])

In [26]:
a, b

(array([[-4, -1],
        [-7, -2]]),
 array([[-4, -7],
        [-1, -2]]))

In [27]:
a = np.array([[2, 0],[0, 1]])
b = np.array([[1, 0],[0, 2]])

a,b

(array([[2, 0],
        [0, 1]]),
 array([[1, 0],
        [0, 2]]))

In [28]:
strategies1 = np.argmax(a, axis=0)
strategies2 = np.argmax(a, axis=1)
strategies1, strategies2

(array([0, 1]), array([0, 1]))

In [41]:
optimal_solutions1 = {(number,strategy) 
                      for number, strategy 
                      in enumerate(strategies1)}
optimal_solutions1

{(0, 0), (1, 1)}

In [42]:
optimal_solutions2 = {(number,strategy) 
                      for number, strategy 
                      in enumerate(strategies2)}
optimal_solutions1

{(0, 0), (1, 1)}

In [43]:
optimal_solutions1.intersection(optimal_solutions2)

{(0, 0), (1, 1)}

In [45]:
!pip install nashpy

  Created wheel for nashpy: filename=nashpy-0.0.20-py3-none-any.whl size=14401 sha256=c41920ee9c616057a9207e8bedc885f942031bc65bd38350b3acf0351e767bfc
  Stored in directory: /home/student/.cache/pip/wheels/68/6f/9a/f02e17185b959b10137b54fd19081b1c83bcfc6b6e9ee1e950
Successfully built nashpy


In [46]:
import nashpy as nash

In [47]:
a = np.array([[-4, -1],[-7, -2]])
b = np.array([[-4, -7],[-1, -2]])

a,b

(array([[-4, -1],
        [-7, -2]]),
 array([[-4, -7],
        [-1, -2]]))

In [53]:
a = np.array([[-1, 1],[1, -1]])
b = np.array([[1, -1],[-1, 1]])

a,b

(array([[-1,  1],
        [ 1, -1]]),
 array([[ 1, -1],
        [-1,  1]]))

In [54]:
rps = nash.Game(a,b)
rps

Zero sum game with payoff matrices:

Row player:
[[-1  1]
 [ 1 -1]]

Column player:
[[ 1 -1]
 [-1  1]]

In [55]:
 eqs = rps.support_enumeration()

In [56]:
list(eqs)

[(array([0.5, 0.5]), array([0.5, 0.5]))]