In [1]:
import torch
import numpy as np

Тензоры 
1. Инициализация

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

Из  массива numpy

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

Из другого тензора

In [8]:
x_ones = torch.ones_like(x_data) # сохраняет свойства x_data
print(f"Единичный Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # переопределяет тип данных x_data
print(f"Случайный Tensor: \n {x_rand} \n")

Единичный Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Случайный Tensor: 
 tensor([[0.7690, 0.7612],
        [0.6022, 0.4937]]) 



In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Случайный Tensor: \n {rand_tensor} \n")
print(f"Единичный Tensor: \n {ones_tensor} \n")
print(f"Нулевой Tensor: \n {zeros_tensor}")

Случайный Tensor: 
 tensor([[0.0542, 0.3351, 0.4440],
        [0.7519, 0.0603, 0.9764]]) 

Единичный Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Нулевой Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


2.Операции над тензорами

In [11]:
tensor = torch.rand(3,4)

print(f"Размерность : {tensor.shape}")
print(f"Тип данных : {tensor.dtype}")
print(f"Устройство хранения: {tensor.device}")

Размерность : torch.Size([3, 4])
Тип данных : torch.float32
Устройство хранения: cpu


In [13]:
#Перенос тензора на GPU
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

print(f"Устройство хранения: {tensor.device}")

Устройство хранения: cuda:0


Индексирование в стиле numpy

In [15]:
tensor = torch.ones(4, 4)
print('Элемент тензора в позиции (1, 2)', tensor[1,2])
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

Элемент тензора в позиции (1, 2) tensor(1.)
First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Присоединение тензоров

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


Арифметические операции

In [26]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [27]:
# Поэлементное умножение. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Тензор из одного элемента

In [19]:
agg = tensor.sum()
agg_item = agg.item()
print(agg, type(agg_item))
print(agg_item, type(agg_item))

tensor(12.) <class 'float'>
12.0 <class 'float'>


Операции, изменяют сам тензор 

In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

Мост к NumPy. 
Tensor to Numpy

In [20]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


Changes in the NumPy array reflects in the tensor.

In [21]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor

In [22]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.

In [23]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
