In [2]:
import torch

In [3]:
probs= torch.tensor([0.6, 0.4])
logits_net = torch.tensor([[0.6, 0.4],[0.5, 0.5]])

In [4]:
distr = torch.distributions.Categorical(probs=probs)
distr.probs

tensor([0.6000, 0.4000])

In [5]:
pi = torch.distributions.Categorical(logits=logits_net)
pi.probs

tensor([[0.5498, 0.4502],
        [0.5000, 0.5000]])

In [6]:
action = pi.sample()
print('log of probs for score function', pi.log_prob(action))
print('log of all probs in dictribution object',torch.log(pi.probs))

log of probs for score function tensor([-0.7981, -0.6931])
log of all probs in dictribution object tensor([[-0.5981, -0.7981],
        [-0.6931, -0.6931]])


In [7]:
torch.log(pi.probs)

tensor([[-0.5981, -0.7981],
        [-0.6931, -0.6931]])

In [12]:
logits_net[...,:1]

tensor([[0.6000],
        [0.5000]])

In [13]:
logits_net[:1,...]

tensor([[0.6000, 0.4000]])